---
title: "Beer Case Study 1"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
#Read both Beer and Brewery csv's
beer = read.csv(file.choose(), header = TRUE)
breweries = read.csv(file.choose(), header = TRUE)

```


```{r}
# 1. How many breweries are present in each state?

#All states with most breweries
TotalStateCount = breweries %>% group_by(State) %>% count(State) %>% arrange(desc(n))

#Top ten states with most breweries.
StateCount = breweries %>% group_by(State) %>% count(State) %>% arrange(desc(n))
StateCount%>%
  head(10)%>%
  ggplot(aes(x=reorder(State,n),y=n, fill=State)) +
  xlab("State")+
  geom_col() + coord_flip() + ggtitle('Top 10 State with the Most Breweries')

```


```{r}
#2.   Merge beer data with the breweries data. Print the first 6 observations and the last six observations to check the merged file.  (RMD only, this does not need to be included in the presentation or the deck.)
library(dplyr)

#Merged both datasets on Brewery ID
merged_data = merge(beer, breweries, by.x = "Brewery_id", by.y = "Brew_ID")

#Renamed columns
colnames(merged_data)[2] = "Beer_Name"
colnames(merged_data)[8] = "Brewery_Name"

#Print the first and last six observations
head(merged_data,6)
tail(merged_data,6)
```

```{r}
#Address the missing values in each column.
#There are 62 missing values in ABV and 1005 missing values in 1005
library(naniar)

#Visualization of NA Values
gg_miss_var(merged_data)

#Display which columns consist of NA values
sapply(merged_data, function(x) sum(is.na(x)))
```

```{r}
# 4.   Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.

#Removed the missing values in the ABV and IBU column.
na_merged_data = merged_data %>% filter(!is.na(ABV) & !is.na(IBU))
#Get the median ABV and median IBU.
median_data = na_merged_data %>% group_by(State) %>% summarize(medianABV = median(ABV), medianIBU = median(IBU))

#created a bar chart comparing the medianABV per state
median_data%>%
  head(10)%>%
  ggplot(aes(x=reorder(State,medianABV),y=medianABV, fill=State)) +
  xlab("State")+
  geom_col() + coord_flip() + ggtitle('Highest Median Alcohol Content by State')


#created a bar chart comparing the medianIBU per state
median_data%>%
  head(10)%>%
  ggplot(aes(x=reorder(State,medianIBU),y=medianIBU, fill=State)) +
  xlab("State")+
  geom_col() + coord_flip() + ggtitle('Highest Median International Bitterness Unit by State')

```

```{r}
#5.Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer?

#Get the Max IBU per state
maxIBU = na_merged_data %>% group_by(State) %>% summarise(MaxIBU.per.State = max(IBU)) %>% arrange(desc(MaxIBU.per.State))

head(maxIBU,3)
head(maxABV,3)

#Plot of the top 3 states with the highest IBU
maxIBU %>%
  head(3)%>%
  ggplot(aes(x=reorder(State,MaxIBU.per.State),y=MaxIBU.per.State, fill=State)) +
  xlab("State")+
  geom_col()  + ggtitle('States with the Highest Max IBU')

#Get the Max ABV per state
maxABV = na_merged_data %>% group_by(State) %>% summarise(MaxABV.per.State = max(ABV)) %>% arrange(desc(MaxABV.per.State))

#Plot of the top 3 states with the highest IBU
maxABV%>%
  head(3)%>%
  ggplot(aes(x=reorder(State,MaxABV.per.State),y=MaxABV.per.State, fill=State)) +
  xlab("State")+
  geom_col()  + ggtitle('States with the Highest Max ABV')
```

```{r}
#6. Comment on the summary statistics and distribution of the ABV variable.

# Box Plot of ABV, IBU and Ounces
theme_USGS_box <- function(base_family = "serif", ...){
  theme_bw(base_family = base_family, ...) +
  theme(
    panel.grid = element_blank(),
    plot.title = element_text(size = 8),
    axis.ticks.length = unit(-0.05, "in"),
    axis.text.y = element_text(margin=unit(c(0.3,0.3,0.3,0.3), "cm")),
    axis.text.x = element_text(margin=unit(c(0.3,0.3,0.3,0.3), "cm")),
    axis.ticks.x = element_blank(),
    aspect.ratio = 1,
    legend.background = element_rect(color = "black", fill = "white")
  )
}
ggplot(na_merged_data, aes( y = ABV)) + geom_boxplot(outlier.colour="red",
                outlier.size=2) + ggtitle('ABV Boxplot with Outliers in Red') + theme_USGS_box()

ggplot(na_merged_data, aes( y = IBU)) + geom_boxplot(outlier.colour="red",
                outlier.size=2) + ggtitle('IBU Boxplot with Outliers in Red') + theme_USGS_box()

ggplot(na_merged_data, aes( y = Ounces)) + geom_boxplot(outlier.colour="red",
                outlier.size=2) + ggtitle('Ounces Boxplot with Outliers in Red') + theme_USGS_box()



#Histogram of ABV
na_merged_data %>% ggplot(aes(x = ABV)) + geom_histogram(fill = "blue", color = "black") + ggtitle('Distribution of ABV Variable')
```


```{r}
# 7.   Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot.  Make your best judgment of a relationship and EXPLAIN your answer.
#Scatter plot of ABV vs. IBU
na_merged_data %>% ggplot(aes(x = ABV, y = IBU)) + geom_point() + geom_smooth(method='lm') + ggtitle('Relationship between ABV and IBU')

```



```{r}
# 8.  Budweiser would also like to investigate the difference with respect to IBU and ABV between IPAs (India Pale Ales) and other types of Ale (any beer with “Ale” in its name other than IPA).  You decide to use KNN classification to investigate this relationship.  Provide statistical evidence one way or the other. You can of course assume your audience is comfortable with percentages … KNN is very easy to understand conceptually.
```

